parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['eus']
    - environmentName: 'tst'
      regionAbrvs: ['eus']
      dependsOnEnv: 'dev'
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'Infrastructure'
- name: serviceName
  type: string
  default: 'loadtestbicep'
stages:
- stage: '${{ parameters.serviceName }}_build'
  jobs:
  - template: jobs/infrastructure_publish_job.yml@templates
    parameters:
      targetPath: ${{ parameters.templateDirectory }}
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
      - template: jobs/bicep_whatif_env_job.yml@templates
        parameters:
          environmentName: ${{ environmentObject.environmentName }}
          templateFileName: ${{ parameters.templateFileName }}
          templateDirectory: ${{ parameters.templateDirectory }}
          serviceName: ${{ parameters.serviceName }}
          regionAbrv: ${{ regionAbrv }}
  - template: jobs/artifact_publish_job.yml@templates
    parameters:
      targetPath: 'tests'
      artifactName: 'tests'
  - template: jobs/zip_publish_job.yml@templates
    parameters:
      artifactName: 'code'
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/code/'
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/bicep_app_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
      packageForLinux: '$(Pipeline.Workspace)/code/*.zip'
      inLineScript: 'npm install'
  - ${{ if eq(variables.runAzureLoadTest, 'true') }} :
    - ${{ each environmentObject in parameters.environmentObjects }} :
      - ${{ if eq(environmentObject.environmentName, 'tst')}}:
        - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
          - template: stages/load_test_stage.yml@templates
            parameters:
              environmentName: ${{ environmentObject.environmentName }}
              regionAbrv: ${{ regionAbrv }}
              loadTestConfigFile: 'tests/SampleApp.yaml'
              serviceName: ${{ parameters.serviceName }}
              envJSONObject: '
                  [
                    {
                    "name": "webapp",
                    "value": "$(webAppName).azurewebsites.net"
                    }
                  ]'
              loadTestResourceName: 'lt-test-dev-eus'
              loadTestResourceGroupName: 'rg-test-dev-eus'
    

